### ISSUE TITLE
Issue with ESP32-S3 and Baudrate 115200 

### ISSUE THREAD

**Issue by rolandschellhorn** [espressif/esptool-js#104]
Many people use this tool to flash their nerdminers, as it seems that some people, myself included, are unable to do so anymore. Specifically, with the Lilygo ESP32-S3, at a baud rate of 115200, it stops at "Stub running..."

**Comment by brianignacio5** [comment]
This might be related to #106. 

Have you tried the latest master ?

**Comment by rolandschellhorn** [comment]
I did not use it recently because there is a simpler solution available now - but I tested it right now and it works again.
So we can close that - thanks.
