### ISSUE TITLE
Live Demo no longer working

### ISSUE THREAD

**Issue by QuirkyCort** [espressif/esptool-js#105]
In commit c34c8c7, index.ts was changed to use .textContent when reading the offset and file data. Since both the offset and file elements are html input elements with no textContent, the demo no longer works. It should be using .value and .data instead.

Relevant lines:
https://github.com/espressif/esptool-js/blob/58df4cdb6f902c7b38dfaf787f212f9f8fb8028f/examples/typescript/src/index.ts#L279

https://github.com/espressif/esptool-js/blob/58df4cdb6f902c7b38dfaf787f212f9f8fb8028f/examples/typescript/src/index.ts#L290

**Comment by RushikeshPatange** [comment]
Yes, when clicking on the **program button**, nothing is happening due to the issue mentioned by @QuirkyCort in the [live demo example.](https://espressif.github.io/esptool-js/) Could you please take a look at it, @brianignacio5? Thank you! 😄

**Comment by brianignacio5** [comment]
Oh apologies for the issue! Will update asap !

**Comment by sdrshnptl** [comment]
Live demo not working again.
Any thought why this might be broken?
![image](https://github.com/espressif/esptool-js/assets/16163372/0a8a3d6b-8df6-445f-abd6-9fed502ded9b)
