### ISSUE TITLE
Make esptool-js available on Android device.

### ISSUE THREAD

**Issue by liux-pro** [espressif/esptool-js#109]
The website https://caniuse.com/?search=webusb indicates that Web USB is available on Android devices. However, it's noted that Web Serial is currently not available on Android, as shown on https://caniuse.com/?search=serial.

To address this limitation, the project at https://github.com/google/web-serial-polyfill has developed a polyfill that enables Web Serial functionality alongside Web USB. This enhancement allows Android devices to access Web Serial capabilities.

I conducted a test by opening the following demonstration on my Android phone: https://googlechromelabs.github.io/serial-terminal/?polyfill. During the test, I successfully connected an ESP32s3 device to my Android phone. This resulted in the display of booting logs from the ESP32 on my Google Chrome browser on Android.

Considering this, I am curious whether the esptool-js project will consider making their tool available for use on Android devices. This expansion could further contribute to the accessibility and functionality of the tool.

**Comment by TD-er** [comment]
Just curious, how did you power the ESP device?
I don't think powering it of the USB from your phone is a good idea.

**Comment by brianignacio5** [comment]
If web serial is supported I believe esptool-js should be as well since it is basically code above the web serial code.
