### ISSUE TITLE
Testing it locally (ESPTOOL-289)

### ISSUE THREAD

**Issue by versamodule** [espressif/esptool-js#11]
Isn't " npn install " missing something after it ? 

https://github.com/espressif/esptool-js#testing-it-locally

**Comment by ameyinamdar** [comment]
Hi @versamodule  "npm install" is already mentioned in https://github.com/espressif/esptool-js#testing-it-locally

**Comment by versamodule** [comment]
Yes, but install what ?

**Comment by ameyinamdar** [comment]
By default, "npm install" uses the package.json file available in the same directory and installs all the dependencies. So you don't have to specify anything explicitly.
