### ISSUE TITLE
Provide Support For All SerialOptions While Opening Port Of Device (Web Serial API)

### ISSUE THREAD

**Issue by RushikeshPatange** [espressif/esptool-js#114]
Currently, only **baudRate** is supported by the **connect** method of **Transport Class**. However, the following options can also be passed when opening the port of the device. For more details, refer to [this link](https://wicg.github.io/serial/#open-method): 

- **dataBits**: The number of data bits per frame (either 7 or 8).
- **stopBits**: The number of stop bits at the end of a frame (either 1 or 2).
- **bufferSize**: The parity mode (either "none", "even", or "odd").
- **parity**: The size of the read and write buffer that should be created (must be less than 16MB).
- **flowControl**: The flow control mode (either "none" or "hardware").

It will be beneficial for devices like ExpressLink, which has specific [serial options](https://github.com/espressif/esp-aws-expresslink-eval#37-set-up-host-machine) configurations while opening the port.

**Comment by brianignacio5** [comment]
Closing this issue thanks to #115
