### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'BOOTLOADER_FLASH_OFFSET')

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esptool-js#119]
[https://espressif.github.io/esptool-js/](https://espressif.github.io/esptool-js/)

was using it like this: 

![](https://github.com/espressif/esptool-js/assets/37779037/05c0fdfb-36e1-4bc2-93a5-c52095bf6fa5)

```
Error: Cannot read properties of undefined (reading 'BOOTLOADER_FLASH_OFFSET')
```

**Comment by balloob** [comment]
Your error is on the line above: Port is already open. Some other process is already reading the serial preventing the page from accessing the serial port.

**Comment by brianignacio5** [comment]
Closing this issue because the error is shown
