### ISSUE TITLE
Browser module imports don't work

### ISSUE THREAD

**Issue by elite174** [espressif/esptool-js#124]
![image](https://github.com/espressif/esptool-js/assets/13636224/611a16d0-9442-4887-ad5c-06b92fc5a43b)

I'm trying to use this lib in the browser without compilation and get this error.

**Comment by elite174** [comment]
try the following code to reproduce
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script type="module">
      import json from "https://unpkg.com/esptool-js@0.3.2/lib/targets/esp32.js?module";
    </script>
  </body>
</html>

```

**Comment by elite174** [comment]
I guess the reason for this this line:
`import ESP32_STUB from "./stub_flasher/stub_flasher_32.json?module";`
The point is that you don't need to use `?module` for json files

**Comment by elite174** [comment]
@brianignacio5 Could you fix this please?

**Comment by brianignacio5** [comment]
How about using the resulting bundle file : https://unpkg.com/esptool-js@0.3.2/bundle.js ?

**Comment by elite174** [comment]
Yes, that would work. But anyways, it's better be fixed

**Comment by elite174** [comment]
Also you need to update README then, because it recommends using https://unpkg.com/esptool-js/lib/index.js?module
