### ISSUE TITLE
Timeout error that feels almost immediate, I may have a solution

### ISSUE THREAD

**Issue by frank26080115** [espressif/esptool-js#151]
I ran into a problem where `erase_flash` was throwing a timeout, but it's supposed to be a timeout of 120000 and it felt like it was immediate.

Investigating with the debugger, it seems like the call `const {value, done} = await reader.read();` was making `done` equal true on the very first call.

Going back a bit, the thing that happens before sending the erase flash command is `main_fn` finishing up with a call to `change_baud`.

At the bottom of `change_baud`, there's a line that says `await this.transport.rawRead({timeout:500});` that has no purpose that I can think of, there's no code comments

Disabling that line `await this.transport.rawRead({timeout:500});` will fix the timeout problem.

Another solution is to simply not call `change_baud` ever, and use baud rate 115200, equaling `rom_baudrate`, so the change is redundant anyways

I hope somebody finds this useful and maybe the code logic gets changed a bit in a release.

I am wondering if this will help the fellas in this issue https://github.com/espressif/esptool-js/issues/96

NOTE: using https://espressif.github.io/esptool-js/ never has this problem but that doesn't mean the problem doesn't exist, it's likely some sort of timing/threading issue, perhaps due to inclusion or absence of xterm. We should aim for a solution that works on all platforms of all variations, not just ignoring an issue because one demo works.

**Comment by brianignacio5** [comment]
Could you try https://brianignacio5.github.io/esptool-js/ which implement #160 ?
