### ISSUE TITLE
Flash error with ESP32-C3 via USB_SERIAL_JTAG: Timeout

### ISSUE THREAD

**Issue by Jason2866** [espressif/esptool-js#41]
```
esptool.js v0.1-dev
Serial port WebSerial VendorID 0x303a ProductID 0x1001
Connecting....
Detecting chip type... ESP32-C3
Chip is ESP32-C3 (revision 3)
Features: Wi-Fi
Crystal is 40MHz
MAC: 84:f7:03:a0:ee:ec
Uploading stub...
Running stub...
Error: Timeout
Compressed 2209028 bytes to 1330626...
```
Screenshot from Chrome Console
<img width="910" alt="Bildschirmfoto 2022-08-11 um 11 00 55" src="https://user-images.githubusercontent.com/24528715/184099513-cc379917-cb92-48a3-8d95-7565f3b95b4e.png">

@balloob fyi

**Comment by Jason2866** [comment]
When using Tasmota WebInstaller which uses `esp-web-flasher` under the hood flashing does work.
<img width="902" alt="Bildschirmfoto 2022-08-11 um 11 08 34" src="https://user-images.githubusercontent.com/24528715/184100914-c989d842-2193-4fc8-a79f-e60c74fc9c9e.png">

**Comment by balloob** [comment]
Maybe the C3 stub is incorrect and so gets stuck once written to RAM https://github.com/espressif/esptool-js/blob/main/targets/esp32c3.js

**Comment by brentru** [comment]
Having the same issue with ESP32-C3.

**Comment by liux-pro** [comment]
same issue

**Comment by TD-er** [comment]
Related? https://github.com/espressif/esptool-js/pull/54

**Comment by Jason2866** [comment]
@brianignacio5  Can you implement in your PR?

**Comment by igrr** [comment]
This should be now fixed by #54, thanks @liux-pro!

**Comment by igrr** [comment]
I thought I tested the final merge commit on both C3 with USB_SERIAL_JTAG and CP2102, but looks like I didn't.

Updating the stub binary seems to solve the issue. I'll do more checks with different boards and open a PR.

**Comment by igrr** [comment]
@liux-pro may I ask you to try https://github.com/espressif/esptool-js/pull/65 and see if that fixes the issue on your end? I've only updated the stub binary for ESP32-C3 there.

**Comment by liux-pro** [comment]
> @liux-pro may I ask you to try #65 and see if that fixes the issue on your end? I've only updated the stub binary for ESP32-C3 there.

Fully functional !

**Comment by Jason2866** [comment]
Confirmed working. Good for release when debugging Infos are removed.

**Comment by igrr** [comment]
#65 has been merged, hopefully this is fixed for good!

**Comment by Histywy** [comment]
esptool.je

Serial port Webserial VendorID 0x10c4 ProductID Oxea60

Connecting... Error: Failed to execute 'open' on 'SerialPort': The port is already open.

I'm having this problem and don't know what the solution is
