### ISSUE TITLE
Time out when trying to flash spiffs.bin for an ESP32

### ISSUE THREAD

**Issue by SeByDocKy** [espressif/esptool-js#49]
Hello, I am trying to flash the spiffs part of a project with this tool.
From pio in verbose mode, the command line executed is : 
```--chip esp32 --port "“COM18”" --baud 460800 --before default_reset --after hard_reset write_flash -z --flash_mode dio                  --flash_size detect 2686976 .pio/build/routeur_solaire/spiffs.bin`````

Seems the offset adress is 2686976 = 0x290000.

When trying with esptool-js got a timeout error...

![image](https://user-images.githubusercontent.com/6464595/196929217-fdeef51e-c7c1-4522-9c21-fde63161639d.png)

Maybe I am wrong somewhere, but is-it a bug ?

**Comment by vidsmet2** [comment]
@SeByDocKy 

I've had the same issue. Changing the baudrate to 115200 solved this.

**Comment by SeByDocKy** [comment]
> @SeByDocKy
> 
> I've had the same issue. Changing the baudrate to 115200 solved this.

Thanks I will try asap :)

**Comment by bpstermometria** [comment]
I have the same issue. any solution?

**Comment by igrr** [comment]
This might be solved by https://github.com/espressif/esptool-js/pull/57. I'd like to compare how esptool.py solves the same issue, though, before merging that PR.
