### ISSUE TITLE
New NPM release with USB_SERIAL_JTAG support

### ISSUE THREAD

**Issue by igrr** [espressif/esptool-js#64]
Now that https://github.com/espressif/esptool-js/pull/54 is merged, we might want to make a new NPM release.

TODOs:

- https://github.com/espressif/esptool-js/pull/65
- https://github.com/espressif/esptool-js/issues/63

**Comment by brianignacio5** [comment]
We could create a tag with new version when major issues are fixed. CI Action [publish](https://github.com/espressif/esptool-js/blob/main/.github/workflows/publish.yml) should work for publish it and release an artifact in GitHub releases.

**Comment by Jason2866** [comment]
+1 for a new release

**Comment by igrr** [comment]
Both linked PRs are now merged, so I think we set the [version](https://github.com/espressif/esptool-js/blob/4bac4457dbed43fdd10b7d64ba3d320291838907/package.json#L3) to 0.2.0 and tag the new release.

**Comment by brianignacio5** [comment]
There is also another small bug fix in #72 we should merge before the release.

**Comment by igrr** [comment]
Released in https://www.npmjs.com/package/esptool-js/v/0.2.0
