### ISSUE TITLE
Move reset code into own function

### ISSUE THREAD

**Issue by balloob** [espressif/esptool-js#76]
The reset code to reset a device is a useful standalone feature. I would like to avoid copying it around to my own projects. Would it be ok to extract it to a standalone function in its own file?

https://github.com/espressif/esptool-js/blob/99bcaf02722afd4e7a9b7f9cbddac4b4de3bc421/src/esploader.ts#L289-L322

**Comment by igrr** [comment]
This does reset into download mode, is that really useful outside of the loader? (Resetting into flash boot mode does indeed seem useful as a standalone function!)

**Comment by balloob** [comment]
oh yeah, I meant that one 😅

**Comment by igrr** [comment]
I see! If you have time, you are welcome to open a PR for that change!
