### ISSUE TITLE
Problem with most current (11.2.0.167) CP210X driver on Windows 10

### ISSUE THREAD

**Issue by dkalliv** [espressif/esptool-js#87]
On Windows 10 systems using the latest  (11.2.0.167) CP210X driver I can not connect to ESP32 devices with a Silicon Labs CP2102 or CP2104 USB to UART bridge. I receive `Error: Timeout`
PlatformIO or the Arduino IDE can connect and flash without issues. When downgrading the driver to version 6.7.4.261, esptool-js works as expected.

**Comment by brentru** [comment]
Hi - also experiencing this with ESP8266 boards and the latest driver.

**Comment by brentru** [comment]
@dkalliv How were you able to downgrade the driver? I don't see any links for version `6.7.4.261` on the SiLabs site.

**Comment by dkalliv** [comment]
On one system I just did a downgrade (only possible if the driver was previously upgraded) for the others I downloaded the drivers from here:
[https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads](url)

**Comment by danielminson** [comment]
I am also experiencing this error! To fix it I selected a driver already available in my computer on device manager
![image](https://user-images.githubusercontent.com/49560569/221376028-502fb466-ea5c-4e92-871c-16488f57a731.png)
Like this:
![image](https://user-images.githubusercontent.com/49560569/221376052-07ceb9a3-2445-40f8-a244-4f9824c6ef52.png)

**Comment by igrr** [comment]
@RushikeshPatange no, I haven't looked at this, I don't have a Windows PC to test with at the moment.

**Comment by brianignacio5** [comment]
Could you try my fork in https://brianignacio5.github.io/esptool-js/ which implement #160 changes ?
