### ISSUE TITLE
Timeout uploading stub on ESP32-S2

### ISSUE THREAD

**Issue by makermelissa** [espressif/esptool-js#91]
I was testing out a few boards. Most are working great, but I'm having an issue with it timing out when uploading the stub on the ESP32-S2. I tried multiple times and at 115200 and 921600.

This was tested with an Adafruit MagTag and the combined.bin file in https://github.com/adafruit/tinyuf2/releases for the board.

Here's the error:
![Screen Shot 2023-03-02 at 4 34 44 PM](https://user-images.githubusercontent.com/2681417/222602880-e9ef1d48-cf7f-4aaa-a725-0c1a4133ef2b.png)

Here's the Console:
<img width="923" alt="Screen Shot 2023-03-02 at 4 43 53 PM" src="https://user-images.githubusercontent.com/2681417/222603374-4fd07ae9-3b01-41b7-bbb7-50d479bb71fd.png">

Thanks.

**Comment by ralphwetzel** [comment]
The same happens here with a M5Atom Lite:

```
esptool.js
Serial port WebSerial VendorID 0x403 ProductID 0x6001
Connecting....
Detecting chip type... ESP32
Chip is ESP32-PICO-D4 (revision 1)
Features: Wi-Fi, BT, Dual Core, 240MHz, Embedded Flash, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 94:b9:7e:a9:9d:38
Uploading stub...
Running stub...
Stub running...
Changing baudrate to 1500000
Changed
Not changing the image
Compressed 17440 bytes to 12131...

Error: Timeout
```

Used to run smoothly with an earlier version => 0.1 !

**Comment by makermelissa** [comment]
@ralphwetzel I think that's a different error as you're getting to the `Stub running...` message and beyond. You may consider trying a slower baud rate, as 1500000 is quite fast and could be causing the timeouts.

Looking through the issues, I think mine may actually a duplicate of #38, which I seemed to have missed when I created this.

**Comment by ralphwetzel** [comment]
> You may consider trying a slower baud rate, as 1500000 is quite fast and could be causing the timeouts.

I did - despite the device usually works perfectly with that baud rate. The error yet stays.
As said, all was fine with an earlier version...

**Comment by jonasniesner** [comment]
I have the same error

**Comment by Jason2866** [comment]
@igrr  Tested with your latest PR and the timeout error is still there

**Comment by igrr** [comment]
This is probably the same issue as https://github.com/espressif/esptool-js/issues/38. I'll close this one as duplicate, please subscribe to that older issue to get notified of the progress.

**Comment by TCB13** [comment]
ESP32-S2 Mini board from Aliexpress [here](https://www.wemos.cc/en/latest/s2/s2_mini.html) failing in ESPHome. To get around this was to manually flash the initial that the web installer (https://web.esphome.io/?dashboard_wizard) normally installs.

I got the image from https://github.com/esphome/firmware/actions/runs/7443385432 then downloaded the esphome-web artifact and extracted the `esphome-web-esp32s2.bin` image to burn using the [Espressif Flash Download Tool](https://www.espressif.com/en/support/download/other-tools) with the address `0x0`.

![Screenshot 2024-01-10 141114](https://github.com/espressif/esptool-js/assets/6315832/4e2515ef-02d8-4f7b-a6e5-186c11b1c1f4)

Make sure DoNotChgBin is checked.

After this I was able to go connect my phone to it, set it to my home wifi network and then go into Home Assistant > ESPHome and flash the final firmware as required.
